### ISSUE TITLE
Optimize Google Chrome audit statistics

### ISSUE THREAD

**Issue by ennukee** [ennukee/aniupdater#32]
## Initial audit
![image](https://user-images.githubusercontent.com/9220151/67951463-eaea6300-fbc1-11e9-80d7-40892c086941.png)

Goal: Bring all of these into the green range

# Task list

- Performance
  - [ ] Turn images into next-gen formats (JPEG 2000, JPEF XR, WebP)
    - [ ] loading_full
    - [ ] loading_small
    - [ ] logo (when made)
  - [ ] Resize `loading_full` to be a proper size matching what it is on the page (currently 1066x1065, but could be around 500x500)
  - [ ] Defer font loading to prevent render-blocking (it's the fonts)
  - [ ] Encode images (likely comes with using next-gen formats)
- Accessibility
  - [ ] Below
![image](https://user-images.githubusercontent.com/9220151/67951926-d3f84080-fbc2-11e9-8af2-eec6f328bff8.png)
  - [ ] Add alt tags to all images
    - [ ] `#loading-anim-div`

NOT FINISHED
