### ISSUE TITLE
Minor change checklist

### ISSUE THREAD

**Issue by ennukee** [ennukee/aniupdater#66]
- [ ] Shrink icons in footer so it's not as cramped
- [ ] Give 'tip' in bottom right a larger gap on the right 
- [ ] Enlarge logo in initial token input?
